name: mobile_computing
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  flutter_map: ^6.1.0
  geocoding: ^2.1.0
  location: ^5.0.3
  go_router: ^13.2.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  nominatim_geocoding: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/

